version: '3'
services:
  # database layer for wordpress >> MySQL Database
  mysql_database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql:/var/lib/mysql
      # wordpress on apache
  wordpress:
    depends_on:
      - mysql_database
    image: wordpress:latest
    restart: always
    ports:
      # expose the port to access from outside of docker container.
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql_database:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: wp_db
    volumes: [ "./:/var/www/html" ]
    #image for phpmyadmin
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mysql_database
      MYSQL_ROOT_PASSWORD: 1234

volumes:
  mysql: {}
